name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "precily" #Must be unique in Heroku
          heroku_email: "sagarmedtiya@gmail.com"
          appdir: "backend"
          procfile: "web: npm start"
          justlogin: true
          working-directory: ./backend
          run: |
            heroku container:login
            heroku container:push --recursive -a precily4
            heroku container:release -a precily4 web
      
        
